### ISSUE TITLE
Polymer version

### ISSUE THREAD

**Issue by aemonge** [AlbertoFdzM/bootstrap-styles#2]
Which version is this supported ?

**Comment by AlbertoFdzM** [comment]
v1 and v2 too.

Pay attention that there will be some limitations when using it due to the shadow DOM avoiding styling inheritance ([more info about polymer styling](https://www.polymer-project.org/2.0/docs/devguide/style-shadow-dom#share-styles-between-elements)).

😄

**Comment by aemonge** [comment]
Thanks a lot !!!!
